GestorVideoJuegos/Controllers/GamerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestorVideoJuegos.Models;

namespace GestorVideoJuegos.Controllers
{
    public class GamerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Gamer/
        public async Task<ActionResult> Index()
        {
            var gamers = db.Gamers.Include(g => g.carrera).Include(g => g.code).Include(g => g.grado).Include(g => g.jornada).Include(g => g.seccion);
            return View(await gamers.ToListAsync());
        }

        // GET: /Gamer/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gamer gamer = await db.Gamers.FindAsync(id);
            if (gamer == null)
            {
                return HttpNotFound();
            }
            return View(gamer);
        }

        // GET: /Gamer/Create
        public ActionResult Create()
        {
            ViewBag.idCarrera = new SelectList(db.Carreras, "idCarrera", "carrera");
            ViewBag.codigo = new SelectList(db.GenerarCodigoes, "idGenerarCodigo", "codigo");
            ViewBag.idGrado = new SelectList(db.Grados, "idGrado", "grado");
            ViewBag.idJornada = new SelectList(db.Jornadas, "idJornada", "jornada");
            ViewBag.idSeccion = new SelectList(db.Seccions, "idSeccion", "seccion");
            return View();
        }

        // POST: /Gamer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="idGamer,Nombres,Apellidos,Carnet,codigo,idCarrera,idGrado,idSeccion,idJornada")] Gamer gamer)
        {
            if (ModelState.IsValid)
            {
                db.Gamers.Add(gamer);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.idCarrera = new SelectList(db.Carreras, "idCarrera", "carrera", gamer.idCarrera);
            ViewBag.codigo = new SelectList(db.GenerarCodigoes, "idGenerarCodigo", "codigo", gamer.codigo);
            ViewBag.idGrado = new SelectList(db.Grados, "idGrado", "grado", gamer.idGrado);
            ViewBag.idJornada = new SelectList(db.Jornadas, "idJornada", "jornada", gamer.idJornada);
            ViewBag.idSeccion = new SelectList(db.Seccions, "idSeccion", "seccion", gamer.idSeccion);
            return View(gamer);
        }

        // GET: /Gamer/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gamer gamer = await db.Gamers.FindAsync(id);
            if (gamer == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCarrera = new SelectList(db.Carreras, "idCarrera", "carrera", gamer.idCarrera);
            ViewBag.codigo = new SelectList(db.GenerarCodigoes, "idGenerarCodigo", "codigo", gamer.codigo);
            ViewBag.idGrado = new SelectList(db.Grados, "idGrado", "grado", gamer.idGrado);
            ViewBag.idJornada = new SelectList(db.Jornadas, "idJornada", "jornada", gamer.idJornada);
            ViewBag.idSeccion = new SelectList(db.Seccions, "idSeccion", "seccion", gamer.idSeccion);
            return View(gamer);
        }

        // POST: /Gamer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="idGamer,Nombres,Apellidos,Carnet,codigo,idCarrera,idGrado,idSeccion,idJornada")] Gamer gamer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gamer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idCarrera = new SelectList(db.Carreras, "idCarrera", "carrera", gamer.idCarrera);
            ViewBag.codigo = new SelectList(db.GenerarCodigoes, "idGenerarCodigo", "codigo", gamer.codigo);
            ViewBag.idGrado = new SelectList(db.Grados, "idGrado", "grado", gamer.idGrado);
            ViewBag.idJornada = new SelectList(db.Jornadas, "idJornada", "jornada", gamer.idJornada);
            ViewBag.idSeccion = new SelectList(db.Seccions, "idSeccion", "seccion", gamer.idSeccion);
            return View(gamer);
        }

        // GET: /Gamer/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gamer gamer = await db.Gamers.FindAsync(id);
            if (gamer == null)
            {
                return HttpNotFound();
            }
            return View(gamer);
        }

        // POST: /Gamer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Gamer gamer = await db.Gamers.FindAsync(id);
            db.Gamers.Remove(gamer);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestorVideoJuegos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestorVideoJuegos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GestorVideoJuegos/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GestorVideoJuegos/Views/Home/Contact.cshtml
@{
	<br/>
    ViewBag.Title = "Log in";
}

<h2>@ViewBag.Title.</h2>
	<div class="row">
		@model GestorVideoJuegos.Models.LoginViewModel
    <div class="row">
        <div class="col-md-8">
            <section id="loginForm">
                @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
					<h4>Use una cuenta de administrador.</h4>
					<hr />
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                           @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })

                            @Html.ValidationMessageFor(m => m.UserName)

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                           @Html.PasswordFor(m => m.Password, new { @class = "form-control" }) @Html.ValidationMessageFor(m => m.Password)

                        </div>

                    </div>

                    <div class="form-group">
                             @*col-md-offset-2 col-md-10*@
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Log in" class="btn btn-default" />
                        </div>
                        </div>

                }
            </section>
        </div>
    </div>

</div>

GestorVideoJuegos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron text-center">
    <h1>REGISTRAR CODIGO</h1>   
	 <input type="text" class="text-center" id="Code" />
		<br />
    <input type="submit" id="registrar" value="Registrar" onclick="ventanaRegistrarGamer();" class="btn btn-success" />
</div>


<script type="text/javascript" >
    
    function clic() {
        var codigo = document.getElementById("Code").value;
        ventanaRegistrarGamer();
    }
</script>

<script>
    function ventanaRegistrarGamer() {
        var url = '@Url.Action("Create.cshtml", "Gamer")';
        $.ajax({
            cache: false,
            async: true,
            type: "GET",
            url: url,
            data: {},
            succes: function (response) {
                $('#resultado').html('');
                $('#resultado').html(response);
            }

        });
    }
</script>

<script >
    function gamer() {
        
    }
</script>
    

GestorVideoJuegos/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Home Page";
}



<div class="row">
    @*<div class="col-md-4">
	<ul>
		<a href="/home"><p4>Eres administrador?</p4></a>
	</ul>
	

    @model GestorVideoJuegos.Models.LoginViewModel

    <div class="row">
        <div class="col-md-8">
            <section id="loginForm">
                @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @*@Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label1" })*@
                        <div class="col-md-10">
                            <h5>UserName @Html.TextBoxFor(m => m.UserName, new { @class = "form-control1" }) </h5>

                            @Html.ValidationMessageFor(m => m.UserName)

                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label1" })*@
                        <div class="col-md-10">
                            <h5>Password @Html.PasswordFor(m => m.Password, new { @class = "form-control1" }) @Html.ValidationMessageFor(m => m.Password)  </h5>

                        </div>

                    </div>

                    <div class="form-group">
                             @*col-md-offset-2 col-md-10*@
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Log in" class="btn btn-default" />
                        </div>
                        </div>

                }
            </section>
        </div>
    </div>

</div>